# service.yaml 
apiVersion: v1 
kind: Service 
metadata: 
  name: mlops-api-service 
spec: 
  selector: 
    app: mlops-api 
  ports: 
    - protocol: TCP 
      port: 5000  # antes era 80 
      targetPort: 5000 
  type: ClusterIP  # antes era LoadBalancer